# Use the latest Ubuntu image as the base
FROM ubuntu:22.04

# Update and upgrade APT packages
RUN apt-get update && apt-get upgrade -y

# Install Python 3 and pip3
RUN apt-get install -y python3 python3-pip

# Install Flask
RUN pip3 install Flask

RUN pip3 install Flask-cors

# Copy the local file api.py to the working directory in the Docker image
COPY api.py /app/api.py

WORKDIR /app

# Set the command to run the Flask app when the container starts
CMD ["python3", "/app/api.py"]

EXPOSE 5252