version: '3.8'

services:
  frontend:
    build: ./front-end
    ports:
      - "9000:9000"
    volumes:
      - ./task4/front-end/softy-pinko-front-end:/var/www/html/softy-pinko-front-end

  backend:
    build: ./back-end
    ports:
      - "5252:5252"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend